# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/voicebot.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'proto/voicebot.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14proto/voicebot.proto\x12\x08voicebot\"\x9d\x01\n\tCallEvent\x12\x0f\n\x07\x63\x61ll_id\x18\x01 \x01(\t\x12\"\n\x06\x63onfig\x18\x02 \x01(\x0b\x32\x10.voicebot.ConfigH\x00\x12%\n\x05\x61udio\x18\x03 \x01(\x0b\x32\x14.voicebot.AudioChunkH\x00\x12)\n\x07\x63ontrol\x18\x05 \x01(\x0b\x32\x16.voicebot.ControlEventH\x00\x42\t\n\x07payload\"=\n\x06\x43onfig\x12\x13\n\x0bsample_rate\x18\x01 \x01(\x05\x12\x1e\n\x05\x63odec\x18\x02 \x01(\x0e\x32\x0f.voicebot.Codec\":\n\nAudioChunk\x12\x0b\n\x03seq\x18\x01 \x01(\x04\x12\x11\n\ttimestamp\x18\x02 \x01(\x04\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\x0c\"M\n\x0c\x43ontrolEvent\x12)\n\x04type\x18\x01 \x01(\x0e\x32\x1b.voicebot.ControlEvent.Type\"\x12\n\x04Type\x12\n\n\x06HANGUP\x10\x00\"g\n\nCallAction\x12%\n\x05\x61udio\x18\x01 \x01(\x0b\x32\x14.voicebot.AudioChunkH\x00\x12\'\n\x07\x63ontrol\x18\x02 \x01(\x0b\x32\x14.voicebot.BotControlH\x00\x42\t\n\x07payload\"p\n\nBotControl\x12\'\n\x04type\x18\x01 \x01(\x0e\x32\x19.voicebot.BotControl.Type\x12\x17\n\x0ftransfer_target\x18\x02 \x01(\t\" \n\x04Type\x12\n\n\x06HANGUP\x10\x00\x12\x0c\n\x08TRANSFER\x10\x01*&\n\x05\x43odec\x12\x08\n\x04PCMU\x10\x00\x12\x08\n\x04PCMA\x10\x08\x12\t\n\x05PCM16\x10\n*%\n\tDirection\x12\n\n\x06UPLINK\x10\x00\x12\x0c\n\x08\x44OWNLINK\x10\x01\x32G\n\x08VoiceBot\x12;\n\nStreamCall\x12\x13.voicebot.CallEvent\x1a\x14.voicebot.CallAction(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.voicebot_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CODEC']._serialized_start=615
  _globals['_CODEC']._serialized_end=653
  _globals['_DIRECTION']._serialized_start=655
  _globals['_DIRECTION']._serialized_end=692
  _globals['_CALLEVENT']._serialized_start=35
  _globals['_CALLEVENT']._serialized_end=192
  _globals['_CONFIG']._serialized_start=194
  _globals['_CONFIG']._serialized_end=255
  _globals['_AUDIOCHUNK']._serialized_start=257
  _globals['_AUDIOCHUNK']._serialized_end=315
  _globals['_CONTROLEVENT']._serialized_start=317
  _globals['_CONTROLEVENT']._serialized_end=394
  _globals['_CONTROLEVENT_TYPE']._serialized_start=376
  _globals['_CONTROLEVENT_TYPE']._serialized_end=394
  _globals['_CALLACTION']._serialized_start=396
  _globals['_CALLACTION']._serialized_end=499
  _globals['_BOTCONTROL']._serialized_start=501
  _globals['_BOTCONTROL']._serialized_end=613
  _globals['_BOTCONTROL_TYPE']._serialized_start=581
  _globals['_BOTCONTROL_TYPE']._serialized_end=613
  _globals['_VOICEBOT']._serialized_start=694
  _globals['_VOICEBOT']._serialized_end=765
# @@protoc_insertion_point(module_scope)
