# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto import voicebot_pb2 as proto_dot_voicebot__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in proto/voicebot_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class VoiceBotStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamCall = channel.stream_stream(
                '/voicebot.VoiceBot/StreamCall',
                request_serializer=proto_dot_voicebot__pb2.CallEvent.SerializeToString,
                response_deserializer=proto_dot_voicebot__pb2.CallAction.FromString,
                _registered_method=True)


class VoiceBotServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StreamCall(self, request_iterator, context):
        """Bidirectional streaming for real-time audio and control
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VoiceBotServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamCall': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamCall,
                    request_deserializer=proto_dot_voicebot__pb2.CallEvent.FromString,
                    response_serializer=proto_dot_voicebot__pb2.CallAction.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'voicebot.VoiceBot', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('voicebot.VoiceBot', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class VoiceBot(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StreamCall(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/voicebot.VoiceBot/StreamCall',
            proto_dot_voicebot__pb2.CallEvent.SerializeToString,
            proto_dot_voicebot__pb2.CallAction.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
